name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Пайплайн будет запускаться при пуше в ветку main
  pull_request:
    branches:
      - main  # Пайплайн будет запускаться при pull request'ах в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Убедитесь, что добавили переменные в Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t kirillermolaev/my-python-server:${{ github.sha }} .
        docker push kirillermolaev/my-python-server:${{ github.sha }}

    - name: Update Helm values.yaml with new image
      run: |
        sed -i 's|image: .*|image: kirillermolaev/my-python-server:${{ github.sha }}|' values.yaml

    - name: Commit updated values.yaml
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add values.yaml
        git commit -m "Update Helm values.yaml with new Docker image"
        git push

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}  # Добавьте ваш kubeconfig в Secrets

    - name: Deploy to Kubernetes with Helm
      run: |
        helm upgrade --install my-python-server ./templates --namespace default --values values.yaml

