apiVersion: v1
kind: Service
metadata:
  name: my-python-server-service
spec:
  selector:
    app: my-python-server  # Привязка к подам с меткой app: my-python-server
  ports:
    - protocol: TCP
      port: 80         # Порт, на который будет направляться внешний трафик
      targetPort: 8000  # Порт внутри контейнера
  type: LoadBalancer   # Для облачных провайдеров, чтобы автоматически получить внешний IP

